### ISSUE TITLE
Body weight in weighted pull-up

### ISSUE THREAD

**Issue by shikhin21** [Shmorty/omni-method#13]
Allow the user to update their body weight when they are entering a value for weighted pull-up.

**Comment by shikhin21** [comment]
@Shmorty 
Do we think that we might need to allow the user to update their body weight in other places (like under other assessments or at some central "user info" section) within the app as well?

Would updating user's weight in weighted pull up (or any other assessment for that matter) also update it in user's info (along with data for that specific assessment) in firestore ? I think that would make sense but want to confirm.

Also, it appears that the current logic to show form fields under a certain assessment is driven based on a configuration file. To make the change required for this issue, it does not seem right to me to just hard code updating of body weight for just one assessment. What do you think?

**Comment by Shmorty** [comment]
This is the only assessment that uses body weight in the score calculation
but i do like the idea of having it configuration driven.
You can use your judgement if you want to make it based on configuration.
We would want it to update the users info in firestore.

**Comment by shikhin21** [comment]
> We would want it to update the users info in firestore.

I can see it being confusing for a user if we update user level info from within an assessment. At some point, we might want to allow users to edit their weight, height etc within the app.. At that point, if a user updates weight from that central place, it would get overridden if the user inputs something different in the assessment - even if they are creating an assessment for a past date.


I think may be a better way would be to pre-populate the user weight in weighted pull up (using user info). They can modify the weight if they want to but then once they save the assessment, only save the data in the assessment.. and then use the weight from the assessment to make the score calculation.

**Comment by Shmorty** [comment]
i see what you’re saying and it makes sense, i think entering past scores
may be rare and we might consolidate older scores to a monthly number to
track and chart progress.

it’d be worth discussing with Raymond, he is available most of the day
outside of a session from 11-12, my daughter has a basketball game at 3 so
maybe we could talk around 12:30 or 1:00 if that works for you?

**Comment by RaymondPlatteel** [comment]
When the user enters their current weight, it wouldn't change their "Bodyweight". Adding their current weight is just to account for shoes, weight belt, clothes, etc. All this extra equipment can add up to 10 lbs of extra weight that needs to be pulled. It would count towards their score but not be saved as their bodyweight.

I think pre-populating the current weight with their bodyweight is still a good idea.
